# Generated by Django 5.0.7 on 2024-08-27 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedface',
            name='face_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tempface',
            name='face_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='selectedface',
            unique_together={('user', 'face_id')},
        ),
    ]
