# Generated by Django 5.0.7 on 2024-09-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempface',
            name='quality_score',
            field=models.FloatField(default=0.0),
        ),
    ]
