# Generated by Django 5.0.7 on 2024-08-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_alter_selectedface_image_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedface',
            name='blur_score',
            field=models.FloatField(default=0.0),
        ),
    ]
