# Generated by Django 5.0.7 on 2024-09-13 02:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_tempface_quality_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.BinaryField(blank=True, null=True)),
                ('detected_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('selected_face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.selectedface')),
            ],
        ),
    ]
