# Generated by Django 5.0.7 on 2024-09-13 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_facevisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facevisit',
            name='selected_face',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_visits', to='camera.selectedface'),
        ),
    ]
