# Generated by Django 5.0.7 on 2024-08-29 05:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_selectedface_blur_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedface',
            name='date_seen',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
