# Generated by Django 5.0.7 on 2024-09-14 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0005_alter_facevisit_selected_face'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedface',
            name='blur_score',
        ),
        migrations.RemoveField(
            model_name='selectedface',
            name='image_data',
        ),
        migrations.RemoveField(
            model_name='selectedface',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='selectedface',
            name='timestamp',
        ),
    ]
