# Generated by Django 5.0.7 on 2024-08-30 06:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0005_selectedface_date_seen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selectedface',
            unique_together={('user', 'face_id', 'date_seen')},
        ),
    ]
