# Generated by Django 5.0.7 on 2024-09-14 02:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0006_remove_selectedface_blur_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedface',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
