# Generated by Django 5.0.7 on 2024-09-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0007_selectedface_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='facevisit',
            name='date_based_image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
