# Generated by Django 5.0.7 on 2024-08-08 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0007_permface_tempface_delete_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempface',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
