# Generated by Django 5.0.7 on 2024-08-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0008_tempface_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempface',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tempface',
            name='processed',
        ),
        migrations.AddField(
            model_name='tempface',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tempface',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.DeleteModel(
            name='PermFace',
        ),
    ]
