# Generated by Django 5.0.7 on 2024-09-16 04:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0008_facevisit_date_based_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedface',
            name='blur_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='selectedface',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selectedface',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
