# Generated by Django 5.0.7 on 2024-08-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0009_remove_tempface_date_remove_tempface_processed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempface',
            name='image_paths',
        ),
        migrations.RemoveField(
            model_name='tempface',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tempface',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='tempface',
            name='image_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
