# Generated by Django 5.0.7 on 2024-09-16 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0009_selectedface_blur_score_selectedface_image_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facevisit',
            name='date_based_image_path',
        ),
    ]
