# Generated by Django 5.0.7 on 2024-08-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0010_remove_tempface_image_paths_remove_tempface_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempface',
            name='image_path',
            field=models.CharField(default=list, max_length=255),
        ),
    ]
