# Generated by Django 5.0.7 on 2024-09-16 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0010_remove_facevisit_date_based_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='facevisit',
            name='date_seen',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
