# Generated by Django 5.0.7 on 2024-09-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0011_facevisit_date_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceanalytics',
            name='face_counts',
        ),
        migrations.RemoveField(
            model_name='faceanalytics',
            name='known_faces',
        ),
        migrations.RemoveField(
            model_name='faceanalytics',
            name='known_faces_all',
        ),
        migrations.RemoveField(
            model_name='faceanalytics',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='faceanalytics',
            name='unknown_faces',
        ),
        migrations.AddField(
            model_name='faceanalytics',
            name='known_faces_month_breakdown',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='faceanalytics',
            name='known_faces_week_breakdown',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='faceanalytics',
            name='known_faces_year_breakdown',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='faceanalytics',
            name='total_known_faces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faceanalytics',
            name='total_unknown_faces',
            field=models.IntegerField(default=0),
        ),
    ]
