# Generated by Django 5.0.7 on 2024-09-18 07:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0012_remove_faceanalytics_face_counts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceanalytics',
            name='known_faces_month_breakdown',
        ),
        migrations.RemoveField(
            model_name='faceanalytics',
            name='known_faces_week_breakdown',
        ),
        migrations.RemoveField(
            model_name='faceanalytics',
            name='known_faces_year_breakdown',
        ),
        migrations.RemoveField(
            model_name='faceanalytics',
            name='total_known_faces',
        ),
        migrations.RemoveField(
            model_name='faceanalytics',
            name='total_unknown_faces',
        ),
        migrations.AddField(
            model_name='faceanalytics',
            name='known_faces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faceanalytics',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='faceanalytics',
            name='unknown_faces',
            field=models.IntegerField(default=0),
        ),
    ]
