# Generated by Django 5.0.7 on 2024-09-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0013_remove_faceanalytics_known_faces_month_breakdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceanalytics',
            name='facecount',
            field=models.JSONField(default=dict),
        ),
    ]
